import numpy as np
import json
import os
import copy
import torch

from typing import Dict,Union,Tuple,List
from tqdm.notebook import trange

import figs.utilities.trajectory_helper as th
import figs.tsplines.min_snap as ms
import sousvide.synthesize.synthesize_helper as sh

from figs.simulator import Simulator
from figs.control.vehicle_rate_mpc import VehicleRateMPC
from figs.dynamics.model_specifications import generate_specifications

def generate_rollout_data(cohort_name:str,method_name:str,
                          flights:List[Tuple[str,str]],
                          expert_name:str="vrmpc_fr",frame_name:str="carl",
                          Nro_sv:int=50):
    
    """
    Generates flight data for a given cohort. A cohort comprises a set of courses flown on a specific
    drone frame with a specific method of domain randomization. Flight data is agnostic to the pilot 
    and is generated by simulating variations of the drone over the set of courses using an MPC flight
    controller that has full knowledge. The flight data is saved to a .pt file in the cohort directory.

    Args:
        cohort_name:    Cohort name.
        method_name:    Sous Vide config.
        flights:        List of flights (scene,frame,course).
        expert_name:    Expert pilot name (usually a vrmpc).
        frame_name:     Quadcopter frame name.
        Nro_sv:         Number of rollouts per save.

    Returns:
        None:           (flight data saved to cohort directory)
    """

    # Some useful path(s)
    workspace_path = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
    
    # Extract method configs
    method_path = os.path.join(workspace_path,"configs","method",method_name+".json")
        
    with open(method_path) as json_file:
        method_config = json.load(json_file)
    
    # Randomization Boundaries
    parameters_bounds = method_config["randomization"]["parameters"]
    initial_bounds = method_config["randomization"]["initial"]

    # Extract expert and frame configs
    expert_path = os.path.join(workspace_path,"configs","pilots",expert_name+".json")
    frame_path  = os.path.join(workspace_path,"configs","frame",frame_name+".json")
    
    with open(expert_path) as json_file:
        expert_config = json.load(json_file)

    with open(frame_path) as json_file:
        base_frame_config = json.load(json_file)   

    # Create cohort folder
    cohort_path = os.path.join(workspace_path,"cohorts",cohort_name)

    if not os.path.exists(cohort_path):
        os.makedirs(cohort_path)

    # Print some useful information
    print("==========================================================================")
    print("Cohort :",cohort_name)
    print("Method :",method_name)
    print("Expert :",expert_name)
    print("Frame  :",frame_name)
    print("Flights:",flights)

    # Generate rollouts for each course
    for scene_name,course_name in flights:
        # Load course_config
        course_path = os.path.join(workspace_path,"configs","course",course_name+".json")

        with open(course_path) as json_file:
            course_config = json.load(json_file)
        
        # Add course name
        course_config["name"] = course_name

        # Generate desired trajectory
        output = ms.solve(course_config)
        if output is not False:
            Tpd,CPd = output
        else:
            raise ValueError("Desired trajectory not feasible. Aborting.")

        # Extract relevant method variables
        rollout_config = method_config["rollout"]
        Tdt_ro = method_config["duration"] or Tpd[-1]
        Ntp_sc = method_config["rate"] or 1/Tdt_ro
        Nro_tp = method_config["reps"] or 1
        tol_select = method_config["tol_select"] or 1e9
        hz_ctl = expert_config["hz"]

        # Generate simulator
        simulator = Simulator(scene_name,rollout_config)
        
        # Generate Sample Set Batches
        Ntp = int(Ntp_sc*Tpd[-1])                                           # Number of time points per trajectory
        Nsp = int(Nro_tp*Ntp)                                               # Number of sample points (total)

        if method_config["duration"] is None:
            Tsp = np.array([Tpd[0]])
        else:
            Tsp = np.tile(np.linspace(Tpd[0],Tpd[-1],Ntp+1)[:-1],Nro_tp)    # Entire sample points array
            Tsp += np.random.uniform(-1/Ntp_sc,1/Ntp_sc,Nsp)                # Add some noise to the sample points array
            Tsp = np.clip(Tsp,Tpd[0],Tpd[-1])                               # Clip the sample points array
        np.random.shuffle(Tsp)                                              # Shuffle the sample points array

        TTsp = np.split(Tsp,np.arange(Nro_sv,Nsp,Nro_sv))                   # Split the sample points array into their batches
        
        # Print some diagnostics
        Ndc = int(Tdt_ro*hz_ctl)

        print("--------------------------------------------------------------------------")
        print("Course Name :",course_name)
        print("Rollout Reps:",Nro_tp,"(per time point)")
        print("Rollout Rate:",np.around(Ntp_sc,3),"(per second)")
        print("Rollout Data:",Ndc,"(per sample)")
        print("--------------------------------------------------------------------------")
        print("Total Rollouts:",Nsp)
        print("Batch Sizes :", len(TTsp)-1, "x", Nro_sv,"+ 1 x", len(TTsp[-1]))
        print("Total Data:",Nsp*Ndc)
        print("--------------------------------------------------------------------------")

        # Generate Sample Set Batches
        Ndata = 0
        for idx in trange(len(TTsp)):
            # Get the current batch
            Tsp = TTsp[idx]
            
            # Generate sample frames
            Frames = generate_frames(Tsp,base_frame_config,parameters_bounds)

            # Generate sample perturbations
            Perturbations  = generate_perturbations(Tsp,Tpd,CPd,initial_bounds)

            # Generate rollout data
            Trajectories,Images = generate_rollouts(
                simulator,course_config,expert_config,
                Frames,Perturbations,Tdt_ro,tol_select,idx)

            # Save the rollout data
            save_rollouts(cohort_path,course_name,Trajectories,Images,idx)

            # Update the data count
            Ndata += sum([trajectory["Ndata"] for trajectory in Trajectories])

        # Print some diagnostics
        print("--------------------------------------------------------------------------")
        print("Generated ",Ndata," points of data.")
        print("--------------------------------------------------------------------------")

def generate_frames(Tsps:np.ndarray,
                    base_frame_config:Dict[str,Union[int,float,List[float]]],
                    parameters_bounds:List[float],
                    rng_seed:Union[int,None]=None) -> List[Dict[str,Union[np.ndarray,str,int,float]]]:
    
    """
    Generates a list of drone variations for a given base drone configuration. The configurations are
    generated by perturbing the base drone configuration with bounded uniform noise. The number of
    configurations generated is determined by the sample set config dictionary.

    Args:
        Tsps:               Sample times.
        base_frame_config:  Base frame configuration dictionary.
        parameters_bounds:  Frame sample set config dictionary.
        rng_seed:           Random number generator seed.

    Returns:
        Drones:             List of drone configurations (dictionary format).
    """

    # TODO: Generalize this to nnio config
    parameters_key = ["mass","force_normalized"]

    # Sample Count
    Nsps = len(Tsps)

    # Set random number generator seed
    if rng_seed is not None:
        np.random.seed(rng_seed)

    # Generate Drone Frames
    Frames = []
    for _ in range(Nsps):
        # Instantiate a new frame
        frame = copy.deepcopy(base_frame_config)

        # Randomize the frame
        for idx,key in enumerate(parameters_key):
            bounds = [-parameters_bounds[idx],parameters_bounds[idx]]
            frame[key] += np.random.uniform(*bounds)

        # Save to a dictionary
        Frames.append(frame)

    return Frames

def generate_perturbations(Tsps:np.ndarray,
                           Tpd:np.ndarray,CPd:np.ndarray,
                           initial_bounds:List[float],
                           rng_seed:int=None) -> List[Dict[str,Union[float,np.ndarray]]]:
    """
    Generates a list of perturbed initial states for the drone given an ideal trajectory. The perturbed
    initial states are generated by sampling a random initial times and corresponding state vectors from
    the ideal trajectory using a bounded uniform distribution. The state vectors are then perturbed with
    uniform noise. The number of perturbed initial states generated is determined by the sample set
    config dictionary.

    Args:
        Tsps:                   Sample times.
        Tpd:                    Ideal trajectory times.
        CPd:                    Ideal trajectory control points.
        initial_bounds:         Initial state bounds.
        rng_seed:               Random number generator seed.

    Returns:
        Perturbations:          List of perturbations (dictionary format).
    """

    # Sample Count
    Nsps = len(Tsps)

    # Set random number generator seed
    if rng_seed is not None:
        np.random.seed(rng_seed)
    
    # Unpack the config
    w_x0 = np.array(initial_bounds,dtype=float)

    # Get ideal trajectory for quaternion checking
    tXUd = th.TS_to_tXU(Tpd,CPd,None,10)

    # Generate perturbed starting points    
    Perturbations = []
    for i in range(Nsps):
        # Sample random start time and get corresponding state vector sample
        t0 = Tsps[i]
        idx0 = np.where(Tpd <= t0)[0][-1]
        idx0 = min(idx0,(len(Tpd)-2))
        t00,t0f = Tpd[idx0],Tpd[idx0 + 1]

        x0s = th.ts_to_xu(t0-t00,t0f-t00,CPd[idx0,:,:],None)
        
        # Perturb state vector sample
        w0 = np.random.uniform(-w_x0,w_x0)
        x0 = x0s + w0
        
        # Ensure quaternion is well-behaved (magnitude and closest to previous)
        idxr = np.where(tXUd[0,:] <= t0)[0][-1]
        x0[6:10] = th.obedient_quaternion(x0[6:10],tXUd[7:11,idxr])

        # Store perturbation in list
        perturbation = {"t0":t0,"x0":x0}
        Perturbations.append(perturbation)
    
    return Perturbations

def generate_rollouts(
        sim:Simulator,
        course_config:Dict[str,Union[np.ndarray,List[np.ndarray]]],
        policy_config:Dict[str,Union[int,float,List[float]]],
        Frames:Dict[str,Union[np.ndarray,str,int,float]],
        Perturbations:Dict[str,Union[float,np.ndarray]],
        Tdt_ro:float,tol_select:float,
        idx_set:int
        ) -> Tuple[List[Dict[str,Union[np.ndarray,np.ndarray,np.ndarray]]],List[torch.Tensor]]:
    """
    Generates rollout data for the quadcopter given a list of drones and initial states (perturbations).
    The rollout comprises trajectory data and image data. The trajectory data is generated by running
    the MPC controller on the quadcopter for a fixed number of steps. The trajectory data consists of
    time, states [p,v,q], body rate inputs [fn,w], objective state, data count, solver timings, advisor
    data, rollout id, and course name. The image data is generated by rendering the quadcopter at each
    state in the trajectory data. The image data consists of the image data and the data count.

    Args:
        simulator:      Simulator object.
        course_config:  Course configuration dictionary.
        policy_config:  Policy configuration dictionary.
        Frames:         List of drone configurations.
        Perturbations:  List of perturbed initial states.
        Tdt_ro:         Rollout duration.
        tol_select:     Error tolerance.
        idx_set:        Index of the rollout set.

    Returns:
        Trajectories:   List of trajectory rollouts.
        Images:         List of image rollouts.
    """
    
    # Unpack the trajectory
    Tpi,CPi = ms.solve(course_config)
    obj = sh.ts_to_obj(Tpi,CPi)
    tXd = th.TS_to_tXU(Tpi,CPi,None,10)
    
    # Initialize rollout variables
    Trajectories,Images = [],[]

    # Rollout the trajectories
    for idx,(frame_config,perturbation) in enumerate(zip(Frames,Perturbations)):
        # Unpack rollout variables
        t0,x0 = perturbation["t0"],perturbation["x0"]
        tf = t0 + Tdt_ro

        # Load the simulation variables
        sim.load_frame(frame_config)
        ctl = VehicleRateMPC(course_config,policy_config,frame_config)
        
        # Simulate the flight
        Tro,Xro,Uro,Iro,Fro,Tsol = sim.simulate(ctl,t0,tf,x0)

        # Check if the rollout data is useful
        err = np.min(np.linalg.norm(tXd[1:4,:]-Xro[0:3,-1].reshape(-1,1),axis=0))
        if err < tol_select:
            # Package the rollout data
            trajectory = {
                "Tro":Tro,"Xro":Xro,"Uro":Uro,"Fro":Fro,
                "tXd":tXd,"obj":obj,"Ndata":Uro.shape[1],"Tsol":Tsol,
                "rollout_id":str(idx_set).zfill(3)+str(idx).zfill(3),
                "course":course_config["name"],
                "frame":frame_config}

            images = {
                "images":Iro,
                "rollout_id":str(idx_set).zfill(3)+str(idx).zfill(3),"course":course_config["name"]
            }

            # Store rollout data
            Trajectories.append(trajectory)
            Images.append(images)

        # Clear policy
        del ctl

    return Trajectories,Images

def save_rollouts(cohort_path:str,course_name:str,
                  Trajectories:List[Tuple[np.ndarray,np.ndarray,np.ndarray]],
                  Images:List[torch.Tensor],
                  stack_id:Union[str,int]) -> None:
    """
    Saves the rollout data to a .pt file in folders corresponding to coursename within the cohort 
    directory. The rollout data is stored as a list of rollout dictionaries of size stack_size for
    ease of comprehension and loading (at a cost of storage space).
    
    Args:
        cohort_path:    Cohort path.
        course_name:    Name of the course.
        Trajectories:   Rollout data.
        Images:         Image data.
        stack_id:       Stack id.

    Returns:
        None:           (rollout data saved to cohort directory)
    """

    # Create rollout course directory (if it does not exist)
    rollout_course_path = os.path.join(cohort_path,"rollout_data",course_name)
    if not os.path.exists(rollout_course_path):
        os.makedirs(rollout_course_path)
    
    # Save the stacks
    dset_name = str(stack_id).zfill(3) if type(stack_id) == int else str(stack_id)
    traj_path = os.path.join(rollout_course_path,"trajectories"+dset_name+".pt")
    imgs_path = os.path.join(rollout_course_path,"images"+dset_name+".pt")

    # Compress the image data
    Images = sh.compress_data(Images)

    torch.save(Trajectories,traj_path)
    torch.save(Images,imgs_path)
